name: CI Pipeline

on:
  push:
    branches:
      - main  # CI wird bei Pushes in den Hauptbranch ausgeführt
  pull_request:
    branches:
      - main  # CI wird bei Pull Requests in den Hauptbranch ausgeführt

jobs:
  test:
    runs-on: ubuntu-latest  # Verwendet die neueste Ubuntu-Version als Umgebung

    steps:
      # Repository klonen
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python installieren
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          hatch env create  # Installiert die Abhängigkeiten aus pyproject.toml
          hatch env run pip install pytest  # Stellt sicher, dass pytest verfügbar ist

      # Tests ausführen
      - name: Run tests
        run: hatch run pytest tests/
